name: Build

on:
  pull_request:
    branches: [master]
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt install -y openjdk-17-jdk make
      - run: java --version
      - run: make
      - run: |
          git config --local user.email "ucum@ucum.org"
          git config --local user.name "UCUM Worker"
          git commit -am 'Generated'
          git push
