on: 
  release:
    types: [published]

name: Release
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Build Artifacts
        run: sudo apt install -y openjdk-17-jdk make && make
      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
          tag_name: ${{ github.event.release.tag_name }}
          release_name: Release...
          prerelease: false
      - name: Upload Asset 1
        id: upload-release-asset1
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./ucum.html
          asset_name: ucum_.html
          asset_content_type: text/html
      - name: Upload Asset 2
        id: upload-release-asset2
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./ucum.xml
          asset_name: ucum_.xml
          asset_content_type: text/xml


