name: Release

on: 
  push:
    tags:
      - '*'

jobs:
  build_release:
    name: Build release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build
        run: sudo apt install -y openjdk-17-jdk make && make
      - name: Create release
        uses: actions/create-release@v1
        id: create_release
        with: 
          tag_name: release-${{ github.ref }}
          release_name: UCUM (Version)
          prerelease: false
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload ucum.html
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ucum.html
          asset_name: ucum_.html
          asset_content_type: text/html
      - name: Upload ucum.xml
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ucum.xml
          asset_name: ucum_.xml
          asset_content_type: text/xml


